# Use postgres/example user/password credentials
version: '3.8'

services:
  server:
    build: .
    ports:
      - 5000:3333
  db:
    image: postgres:16
    ports: 
      - 2345:5432
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes: 
      # - data:/var/lib/postgresql/data

# volumes:
  # data: