version: '3.8'

services:
  db:
    image: postgres:16
    ports: 
      - 5432:5432
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes: 
      # - data:/var/lib/postgresql/data
    # networks:
    #   - sandbox
  server:
    build: .
    ports:
      - 5000:3333
    # networks:
    #   - sandbox
    depends_on:
      - db
# volumes:
  # data: