###

POST http://localhost:5000/auth/signin

###

GET http://localhost:5000/auth/signup

###
POST  http://localhost:3333/auth/signup
content-type: application/json

{
    "email": "qwe@qwe.qwerty",
    "password": "qwerty",
    "passwordConfirm": "qwerty",
    "login": "qwerty"
}

###
POST  http://localhost:3333/auth/signin
content-type: application/json

{
    "password": "qwerty",
    "login": "qwerty"
}